# Generated by Django 3.1.dev20200327073858 on 2020-05-06 02:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200408_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
