# Generated by Django 3.1.dev20200327073858 on 2020-05-19 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200518_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
