# Generated by Django 3.1.dev20200327073858 on 2020-05-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20200521_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
