# Generated by Django 3.1.dev20200327073858 on 2020-05-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_comment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
