# Generated by Django 3.1.dev20200327073858 on 2020-06-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20200605_2359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
